# Tutorial

In [11]:
from risma import AquariusWebPortal

## Establish connection to the website

To demonstrate I'll create three connections to different examples of Aquarius Web Portal implementations, all configured in different ways, using different versions of the software.

In [12]:
aafc = AquariusWebPortal(server="agrifood.aquaticinformatics.net", auto_accept_disclaimer=True)

## Getting a list of parameters

For some portals you can get back a list of parameters:

In [13]:
params = aafc.fetch_params()
params

   param_id        param_name                      param_desc
0        18          Air Temp                 Air Temperature
1        21        Atmos Pres            Atmospheric Pressure
2       116         Dew Point           Dew Point Temperature
3       144         Discharge                       Discharge
4         1             Stage   Height of Gauge (River Stage)
5        95      Precip Total             Precipitation Total
6       121               ETo    Reference Evapotranspiration
7        24      Rel Humidity               Relative Humidity
8        98     Soil Moisture        Soil Moisture, by volume
9       124  Soil temperature                Soil temperature
10       22         Solar Rad  Total Incoming Solar Radiation
11      125    Water Pressure                  Water Pressure
12      100        Water Temp               Water Temperature
13       19          Wind Dir                  Wind Direction
14        8     Wind Gust Vel                 Wind Gust speed
15      107          Wind Vel                      Wind Speed

## Getting a list of locations (sites)

For either type of portal you can fetch a list of locations:

In [14]:
risma_stations = ["RISMA_MB1", "RISMA_MB2", "RISMA_MB3", "RISMA_MB4", "RISMA_MB5", "RISMA_MB6", "RISMA_MB7", "RISMA_MB8"]

stations = aafc.fetch_locations(stations=risma_stations)
print(stations.shape)
stations.head()

(8, 10)

,wp_loc_id,lon,lat,loc_name,loc_id,loc_type,loc_folder,classification,bgcolor,seq
1,1523,-98.01924,49.56234,RISMA Manitoba Station 1,RISMA_MB1,RISMA Station,All Locations.Public.RISMA,-,#FFFFFF,0
13,1548,-97.93374,49.49250,RISMA Manitoba Station 2,RISMA_MB2,RISMA Station,All Locations.Public.RISMA,-,#FFFFFF,0
21,1524,-97.95649,49.51951,RISMA Manitoba Station 3,RISMA_MB3,RISMA Station,All Locations.Public.RISMA,-,#FFFFFF,0
22,1525,-97.98813,49.63609,RISMA Manitoba Station 4,RISMA_MB4,RISMA Station,All Locations.Public.RISMA,-,#FFFFFF,0
23,1526,-97.95781,49.62145,RISMA Manitoba Station 5,RISMA_MB5,RISMA Station,All Locations.Public.RISMA,-,#FFFFFF,0

## Getting a list of datasets for portals which are not blocked by a disclaimer

Now let's say you want a complete list of datasets (time-series). We can obtain this by querying the website for a particular parameter.

If the portal you are using does not have a disclaimer, you are in luck. You could either iterate over all the parameters, or just those which you are interested in:

In [15]:
level_params = params[params.param_name.isin(['Air Temp', 'Soil temperature', 'Soil Moisture'])]
level_params

  param_id        param_name                param_desc
0       18          Air Temp           Air Temperature
8       98     Soil Moisture  Soil Moisture, by volume
9      124  Soil temperature          Soil temperature

In [16]:
datasets = aafc.fetch_datasets(param_names=level_params.param_name.tolist(), stations=stations.loc_id.tolist(), sensors=['1', '2', '3'], depths=['0 to 5 cm', '5 cm'])
print(datasets.shape)
datasets.head()

(104, 19)

,wp_loc_id,wp_dset_id,lon,lat,loc_name,loc_id,dset_name,loc_type,loc_folder,dset_start,dset_end,classification,bgcolor,seq,param,label,type,depth,sensor
43,1523,50358,-98.01924,49.56234,RISMA Manitoba Station 1,RISMA_MB1,Air Temp.Air temperature@RISMA_MB1,RISMA Station,All Locations.Public.RISMA,2013-04-16T12:00:00,2025-07-08T16:00:00,-,#FFFFFF,0,Air Temp,Air temperature,air,NaN,NaN
445,1548,50581,-97.93374,49.49250,RISMA Manitoba Station 2,RISMA_MB2,Air Temp.Air temperature@RISMA_MB2,RISMA Station,All Locations.Public.RISMA,2013-06-14T18:15:00,2025-07-08T16:00:00,-,#FFFFFF,0,Air Temp,Air temperature,air,NaN,NaN
741,1524,50568,-97.95649,49.51951,RISMA Manitoba Station 3,RISMA_MB3,Air Temp.Air temperature@RISMA_MB3,RISMA Station,All Locations.Public.RISMA,2013-06-14T18:15:00,2025-07-08T16:00:00,-,#FFFFFF,0,Air Temp,Air temperature,air,NaN,NaN
771,1525,50544,-97.98813,49.63609,RISMA Manitoba Station 4,RISMA_MB4,Air Temp.Air temperature@RISMA_MB4,RISMA Station,All Locations.Public.RISMA,2013-06-14T18:15:00,2025-07-08T15:00:00,-,#FFFFFF,0,Air Temp,Air temperature,air,NaN,NaN
816,1526,50603,-97.95781,49.62145,RISMA Manitoba Station 5,RISMA_MB5,Air Temp.Air temperature@RISMA_MB5,RISMA Station,All Locations.Public.RISMA,2013-06-14T18:15:00,2025-07-08T16:00:00,-,#FFFFFF,0,Air Temp,Air temperature,air,NaN,NaN

The key fields for datasets are:

In [18]:
datasets[["loc_id", "loc_name", "param", "label", "dset_start", "dset_end"]].head(25)

,loc_id,loc_name,param,label,dset_start,dset_end
43,RISMA_MB1,RISMA Manitoba Station 1,Air Temp,Air temperature,2013-04-16T12:00:00,2025-07-08T16:00:00
445,RISMA_MB2,RISMA Manitoba Station 2,Air Temp,Air temperature,2013-06-14T18:15:00,2025-07-08T16:00:00
741,RISMA_MB3,RISMA Manitoba Station 3,Air Temp,Air temperature,2013-06-14T18:15:00,2025-07-08T16:00:00
771,RISMA_MB4,RISMA Manitoba Station 4,Air Temp,Air temperature,2013-06-14T18:15:00,2025-07-08T15:00:00
816,RISMA_MB5,RISMA Manitoba Station 5,Air Temp,Air temperature,2013-06-14T18:15:00,2025-07-08T16:00:00
859,RISMA_MB6,RISMA Manitoba Station 6,Air Temp,Air temperature,2013-06-14T18:15:00,2025-07-08T16:00:00
897,RISMA_MB7,RISMA Manitoba Station 7,Air Temp,Air temperature,2013-06-14T18:15:00,2025-07-08T16:00:00
946,RISMA_MB8,RISMA Manitoba Station 8,Air Temp,Air temperature,2013-06-14T18:15:00,2025-07-08T16:00:00
28,RISMA_MB1,RISMA Manitoba Station 1,Soil temperature,Soil temperature 5 cm depth sensor 3,2013-04-16T12:00:00,2025-07-08T16:00:00
30,RISMA_MB1,RISMA Manitoba Station 1,Soil Moisture,Soil water content 0 to 5 cm depth sensor 1,2013-04-16T12:00:00,2025-07-08T16:00:00
32,RISMA_MB1,RISMA Manitoba Station 1,Soil Moisture,Soil water content 0 to 5 cm depth sensor 3,2013-04-16T12:00:00,2025-07-08T16:00:00
34,RISMA_MB1,RISMA Manitoba Station 1,Soil temperature,Soil temperature 5 cm depth sensor 1,2013-04-16T12:00:00,2023-03-13T00:00:00
37,RISMA_MB1,RISMA Manitoba Station 1,Soil Moisture,Soil water content 5 cm depth sensor 2,2013-04-16T12:00:00,2025-07-08T16:00:00
41,RISMA_MB1,RISMA Manitoba Station 1,Soil temperature,Soil temperature 0 to 5 cm depth sensor 3,2013-04-16T12:00:00,2025-07-08T16:00:00
44,RISMA_MB1,RISMA Manitoba Station 1,Soil Moisture,Soil water content 5 cm depth sensor 3,2013-04-16T12:00:00,2025-07-08T16:00:00
45,RISMA_MB1,RISMA Manitoba Station 1,Soil temperature,Soil temperature 5 cm depth sensor 2,2013-04-16T12:00:00,2025-07-08T16:00:00
47,RISMA_MB1,RISMA Manitoba Station 1,Soil Moisture,Soil water content 5 cm depth sensor 1,2013-04-16T12:00:00,2023-03-13T00:00:00
49,RISMA_MB1,RISMA Manitoba Station 1,Soil Moisture,Soil water content 0 to 5 cm depth sensor 2,2013-04-16T12:00:00,2025-07-08T16:00:00
51,RISMA_MB1,RISMA Manitoba Station 1,Soil temperature,Soil temperature 0 to 5 cm depth sensor 2,2013-04-16T12:00:00,2025-07-08T16:00:00
54,RISMA_MB1,RISMA Manitoba Station 1,Soil temperature,Soil temperature 0 to 5 cm depth sensor 1,2013-04-16T12:00:00,2025-07-08T16:00:00
437,RISMA_MB2,RISMA Manitoba Station 2,Soil Moisture,Soil water content 0 to 5 cm depth sensor 3,2013-06-14T18:15:00,2025-07-08T16:00:00
438,RISMA_MB2,RISMA Manitoba Station 2,Soil Moisture,Soil water content 5 cm depth sensor 3,2013-06-14T18:15:00,2025-07-08T16:00:00
439,RISMA_MB2,RISMA Manitoba Station 2,Soil temperature,Soil temperature 5 cm depth sensor 2,2013-06-17T13:15:00,2025-07-08T16:00:00
441,RISMA_MB2,RISMA Manitoba Station 2,Soil temperature,Soil temperature 0 to 5 cm depth sensor 3,2013-06-14T18:15:00,2025-07-08T16:00:00
446,RISMA_MB2,RISMA Manitoba Station 2,Soil temperature,Soil temperature 5 cm depth sensor 1,2013-06-14T18:15:00,2025-07-08T16:00:00

Note also that Aquarius combines these into what they call a dataset name:

``{param}.{label}@{location_id}``

In [19]:
datasets[["param", "label", "loc_id", "dset_name"]].head(25)

,param,label,loc_id,dset_name
43,Air Temp,Air temperature,RISMA_MB1,Air Temp.Air temperature@RISMA_MB1
445,Air Temp,Air temperature,RISMA_MB2,Air Temp.Air temperature@RISMA_MB2
741,Air Temp,Air temperature,RISMA_MB3,Air Temp.Air temperature@RISMA_MB3
771,Air Temp,Air temperature,RISMA_MB4,Air Temp.Air temperature@RISMA_MB4
816,Air Temp,Air temperature,RISMA_MB5,Air Temp.Air temperature@RISMA_MB5
859,Air Temp,Air temperature,RISMA_MB6,Air Temp.Air temperature@RISMA_MB6
897,Air Temp,Air temperature,RISMA_MB7,Air Temp.Air temperature@RISMA_MB7
946,Air Temp,Air temperature,RISMA_MB8,Air Temp.Air temperature@RISMA_MB8
28,Soil temperature,Soil temperature 5 cm depth sensor 3,RISMA_MB1,Soil temperature.Soil temperature 5 cm depth s...
30,Soil Moisture,Soil water content 0 to 5 cm depth sensor 1,RISMA_MB1,Soil Moisture.Soil water content 0 to 5 cm dep...
32,Soil Moisture,Soil water content 0 to 5 cm depth sensor 3,RISMA_MB1,Soil Moisture.Soil water content 0 to 5 cm dep...
34,Soil temperature,Soil temperature 5 cm depth sensor 1,RISMA_MB1,Soil temperature.Soil temperature 5 cm depth s...
37,Soil Moisture,Soil water content 5 cm depth sensor 2,RISMA_MB1,Soil Moisture.Soil water content 5 cm depth se...
41,Soil temperature,Soil temperature 0 to 5 cm depth sensor 3,RISMA_MB1,Soil temperature.Soil temperature 0 to 5 cm de...
44,Soil Moisture,Soil water content 5 cm depth sensor 3,RISMA_MB1,Soil Moisture.Soil water content 5 cm depth se...
45,Soil temperature,Soil temperature 5 cm depth sensor 2,RISMA_MB1,Soil temperature.Soil temperature 5 cm depth s...
47,Soil Moisture,Soil water content 5 cm depth sensor 1,RISMA_MB1,Soil Moisture.Soil water content 5 cm depth se...
49,Soil Moisture,Soil water content 0 to 5 cm depth sensor 2,RISMA_MB1,Soil Moisture.Soil water content 0 to 5 cm dep...
51,Soil temperature,Soil temperature 0 to 5 cm depth sensor 2,RISMA_MB1,Soil temperature.Soil temperature 0 to 5 cm de...
54,Soil temperature,Soil temperature 0 to 5 cm depth sensor 1,RISMA_MB1,Soil temperature.Soil temperature 0 to 5 cm de...
437,Soil Moisture,Soil water content 0 to 5 cm depth sensor 3,RISMA_MB2,Soil Moisture.Soil water content 0 to 5 cm dep...
438,Soil Moisture,Soil water content 5 cm depth sensor 3,RISMA_MB2,Soil Moisture.Soil water content 5 cm depth se...
439,Soil temperature,Soil temperature 5 cm depth sensor 2,RISMA_MB2,Soil temperature.Soil temperature 5 cm depth s...
441,Soil temperature,Soil temperature 0 to 5 cm depth sensor 3,RISMA_MB2,Soil temperature.Soil temperature 0 to 5 cm de...
446,Soil temperature,Soil temperature 5 cm depth sensor 1,RISMA_MB2,Soil temperature.Soil temperature 5 cm depth s...

In [ ]:
# groupby datasets based on loc_id
gp_df = datasets.groupby('loc_id')
for station, df in gp_df:
    print(f'{station}')
    st_df = aafc.fetch_dataset(dset_names=df.dset_name.to_list(), start="2010-05-01", end="2022-05-02", extra_data_types=None)
    print(st_df.shape)

    # Save the DataFrame to a CSV file named 'data.csv'
    st_df.to_csv(f'{station}.csv', index=False)
    break

RISMA_MB1
Disclaimer form not found in the expected format. Skipping disclaimer acceptance.

/home/debian/usask_work/RISMA/src/risma/main.py:411: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f, header=None, sep=",")

(316508, 14)

In [22]:
df_fin = aafc.fetch_dataset(dset_names=datasets.dset_name.to_list(), start="2022-01-01", finish="2022-02-01", extra_data_types=None)
df_fin

Disclaimer form not found in the expected format. Skipping disclaimer acceptance.

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
0,#Bulk Export - Points as recorded,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"DISCLAIMER: By exporting the file, you acknowl...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,RISMA_MB1,RISMA_MB2,RISMA_MB3,RISMA_MB4,RISMA_MB5,RISMA_MB6,RISMA_MB7,RISMA_MB8,RISMA_MB1,...,RISMA_MB3,RISMA_MB3,RISMA_MB3,RISMA_MB3,RISMA_MB4,RISMA_MB4,RISMA_MB4,RISMA_MB4,RISMA_MB4,RISMA_MB4
3,NaN,RISMA Manitoba Station 1,RISMA Manitoba Station 2,RISMA Manitoba Station 3,RISMA Manitoba Station 4,RISMA Manitoba Station 5,RISMA Manitoba Station 6,RISMA Manitoba Station 7,RISMA Manitoba Station 8,RISMA Manitoba Station 1,...,RISMA Manitoba Station 3,RISMA Manitoba Station 3,RISMA Manitoba Station 3,RISMA Manitoba Station 3,RISMA Manitoba Station 4,RISMA Manitoba Station 4,RISMA Manitoba Station 4,RISMA Manitoba Station 4,RISMA Manitoba Station 4,RISMA Manitoba Station 4
4,NaN,Air Temp.Air temperature,Air Temp.Air temperature,Air Temp.Air temperature,Air Temp.Air temperature,Air Temp.Air temperature,Air Temp.Air temperature,Air Temp.Air temperature,Air Temp.Air temperature,Soil temperature.Soil temperature 5 cm depth s...,...,Soil temperature.Soil temperature 0 to 5 cm de...,Soil temperature.Soil temperature 0 to 5 cm de...,Soil Moisture.Soil water content 0 to 5 cm dep...,Soil Moisture.Soil water content 5 cm depth se...,Soil temperature.Soil temperature 0 to 5 cm de...,Soil temperature.Soil temperature 5 cm depth s...,Soil Moisture.Soil water content 5 cm depth se...,Soil temperature.Soil temperature 5 cm depth s...,Soil Moisture.Soil water content 0 to 5 cm dep...,Soil Moisture.Soil water content 5 cm depth se...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3051,2022-01-31 23:00:00,-2.70,-3.71,-3.20,-3.36,-3.56,-3.86,-3.60,-4.32,-4.60,...,-8.00,-8.50,0.1,0.12,-5.50,-5.10,0.032,-4.80,NaN,NaN
3052,2022-01-31 23:15:00,-2.13,-2.67,-1.30,-2.65,-2.64,-3.71,-3.16,-3.75,-4.60,...,-7.90,-8.50,0.1,0.12,-5.40,-5.00,0.029,-4.70,NaN,NaN
3053,2022-01-31 23:30:00,-1.05,-1.51,-0.33,-0.73,-1.54,-1.93,-0.98,-2.26,-4.60,...,-7.80,-8.40,0.11,0.12,-5.30,-5.00,0.036,-4.70,NaN,NaN
3054,2022-01-31 23:45:00,-1.51,-1.90,-1.08,-0.86,-1.01,-0.85,-1.28,-1.01,-4.60,...,-7.70,-8.40,0.11,0.12,-5.30,-5.00,0.032,-4.60,NaN,NaN
3055,2022-02-01 00:00:00,-1.98,-2.28,-1.44,-1.32,-1.53,-1.38,-1.76,-3.71,-4.60,...,-7.60,-8.20,0.1,0.12,-5.30,-5.00,0.036,-4.60,NaN,NaN